### ISSUE TITLE
Set font size of node labels

### ISSUE THREAD

**Issue by Goncalerta** [dmfrodrigues/GraphViewerCpp#11]
I'm not sure if I'm missing something in the documentation, but I wasn't able to find a way to set the size of a label in a node. And currently my labels do not fit the nodes so I'd like to shrink them a bit.

![image](https://user-images.githubusercontent.com/22060232/117891244-7a3ffe80-b2ae-11eb-8ca3-108eb333dcaa.png)

Is there currently a way to do this?

**Comment by dmfrodrigues** [comment]
@Goncalerta there is currently not a simple way to do that. The only way that is currently working is to up-scale nodes/edges by a certain factor so that the text is not as large when compared to nodes/edges.

Will be worked on for v1.1.0.

**Comment by dmfrodrigues** [comment]
Fixed in aff332c. Bear in mind that reducing label character size using `setLabelSize` may cause the label to render poorly, which is a limitation of SFML.
