### ISSUE TITLE
gv.setCenter() after window is created

### ISSUE THREAD

**Issue by Goncalerta** [dmfrodrigues/GraphViewerCpp#12]
After calling `gv.createWindow(1800, 1000);` on a GraphViewer instance `gv`, every time I call `gv.setCenter(sf::Vector2f(newX, newY));` the window crashes. I tried with and without using `gv.lock()` and it didn't work in either case.

I'm not sure if I'm doing something wrong or if it is a bug. If you need more information, let me know

**Comment by dmfrodrigues** [comment]
Will investigate

**Comment by dmfrodrigues** [comment]
Could replicate, investigating a fix.

**Comment by dmfrodrigues** [comment]
Bug fixed in 0e51959.
