### ISSUE TITLE
unlock of unowned mutex?

### ISSUE THREAD

**Issue by Goncalerta** [dmfrodrigues/GraphViewerCpp#16]
When running version 1.2.0, when creating the window I'm getting 
d:\agent\_work\3\s\src\vctools\crt\crtw32\stdcpp\thr\mutex.c(175): unlock of unowned mutex

I thought this problem could have been caused by
https://github.com/dmfrodrigues/GraphViewerCpp/blob/efd90a9dcbe3e248aa0ec0f9a1ad7e7993131100/src/graphviewer.cpp#L70

But it still persists after removing that line. I'm not sure what is wrong

**Comment by dmfrodrigues** [comment]
Found the problem. It is related to the fact the mutex is locked by the main thread and unlocked by the event-handling thread. According to the [docs of unlock()](https://en.cppreference.com/w/cpp/thread/mutex/unlock), this is undefined behavior.

In practice it does not make much sense to unlock from a thread other than the one that locked, but the solution seemed to work at some point. Linux handles it fine (its undefined behavior is just to ignore the fact it is being unlocked from a thread other than the one that locked it), but MSVC doesn't agree with that (and rightfully so).

Most likely will implement that decently as a condition variable+mutex.

**Comment by dmfrodrigues** [comment]
@Goncalerta please check if the bug is fixed in commit e0beb02 (current head of branch dev).

**Comment by Goncalerta** [comment]
It seems to be working properly now, thanks!
